# 1. Default config for local development.
spring:
  application:
    name: lms-gateway-service
  config:
    # Use the local hostname when no profile is specified
    import: "optional:configserver:http://localhost:9000"
    fail-fast: true
    retry:
      initial-interval: 1000 # 1second
      max-interval: 5000
      max-attempts: 20

logging:
  level:
    org.springframework.cloud.config: DEBUG

--- # doc separator

## 2. Docker profile config
spring:
  config:
    activate:
      on-profile: docker
    import: "configserver:http://config-server:9000"

logging:
  level:
    org.springframework.cloud.config: DEBUG